# -*- coding: utf-8 -*-
"""Colab 구독 최대한 활용하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/pro.ipynb
"""

import nltk
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

input_sentence = "We should all study hard for the exam"
print(f"{input_sentence}")

