# -*- coding: utf-8 -*-
"""Colab 구독 최대한 활용하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/isbin1007/tutorial/blob/master/LLM_TestCode.ipynb
"""

import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

input_sentence = "We should all study hard for the exam"
print(f"{input_sentence}")

stop_words = set(stopwords.words('english'))
word_tokens = word_tokenize(input_sentence)
result = []
for w in word_tokens:
  if w not in stop_words:
    result.append(w)
print(word_tokens)
print(result)

